run:
  build-tags:
    - apitests
  deadline: 8m
  skip-files:
    - ziti/cmd/edge/verify_ca.go

# golangci gives false positives for implementations of methods using generics in generic interfaces
issues:
  exclude-rules:
    - path: 'controller/model/.*.go'
      linters:
        - unused
