version: '3.3'
services:
    dns:
        restart: "no"
        image: strm/dnsmasq
        volumes:
        - ./dnsmasq.conf:/etc/dnsmasq.conf
        network_mode: host
        cap_add:
        - NET_ADMIN
